version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nambakadai-postgres
    environment:
      POSTGRES_DB: nambakadai
      POSTGRES_USER: nambakadai_user
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: nambakadai-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data: